AWSTemplateFormatVersion: "2010-09-09"
Description: Simple random service. Version 1.0.0
Parameters:
  dockerhubRepositoryName:
    Type: String
    Description: Enter dockerhub repository name
  dockerImageTag:
    Type: String
    Description: Enter docker image tag
    Default: latest
  serviceDesiredCount:
    Type: Number
    Description: Enter tasks desired count
    Default: 2
    MinValue: 1
  containerMemoryReservation:
    Type: Number
    Description: Memory reservation for one task
    Default: 64
    AllowedValues:
      - 32
      - 64
      - 96
      - 128
      - 160
      - 192
      - 256
      - 224
  containerMemoryLimit:
    Type: Number
    Description: Memory limit for task
    Default: 96
    AllowedValues:
      - 64
      - 96
      - 128
      - 160
      - 192
      - 256
      - 224
      - 256
  containerCpuReservation:
    Type: Number
    Description: CPU Reservation for one task
    Default: 24
    AllowedValues:
      - 0
      - 8
      - 16
      - 24
      - 32
      - 48
      - 64
Resources:
  taskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !ImportValue simple-ecs-task-execution-role
      Family: simple-random-service
      ContainerDefinitions:
        -
          Name: simple-random-service
          Image: !Sub ${dockerhubRepositoryName}:${dockerImageTag}
          MemoryReservation: !Ref containerMemoryReservation
          Memory: !Ref containerMemoryLimit
          Cpu: !Ref containerCpuReservation
          Essential: true
          PortMappings:
            -
              HostPort: 0
              Protocol: tcp
              ContainerPort: 8000
  targetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 15
      HealthCheckPath: "/health-check"
      HealthCheckProtocol: "HTTP"
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Name: simple-random-app
      Port: 80
      Protocol: "HTTP"
      TargetGroupAttributes:
        -
          Key: "deregistration_delay.timeout_seconds"
          Value: "60"
      VpcId: !ImportValue simple-vpc     
  service:
    Type: AWS::ECS::Service
    DependsOn: albListenersRulePort80
    Properties:
      Cluster: !ImportValue simple-cluster-logical-id
      ServiceName: simple-random-service
      DesiredCount: !Ref serviceDesiredCount
      LoadBalancers:
        - 
          ContainerName: simple-random-service
          ContainerPort: 8000
          TargetGroupArn: !Ref targetGroup
      Role: !ImportValue simple-ecs-service-role
      TaskDefinition: !Ref taskDefinition
      PlacementStrategies:
        - Field: "attribute:ecs.availability-zone"
          Type: "spread"
        - Field: "instanceId"
          Type: "spread"
      HealthCheckGracePeriodSeconds: 15
  albListenersRulePort80:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref 'targetGroup'
      Conditions:
      - Field: path-pattern
        Values: [/api/random-number]
      ListenerArn: !ImportValue 'simple-alb-listener-port-80'
      Priority: 1
  taskEssentialExitEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: simple-ecs-task-essential-exit-rule
      Description: "Rule which keeps record of task exit events"
      EventPattern: !Sub 
        - | 
            {
              "source": [
                "aws.ecs"
              ],
              "detail-type": [
                "ECS Task State Change"
              ],
              "detail": {
                "clusterArn": ["arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ecsCluster}"],
                "taskDefinitionArn": ["${taskDefinition}"],
                "stoppedReason": ["Essential container in task exited"]
              }
            }
        - ecsCluster: 
            Fn::ImportValue: simple-cluster-logical-id
      State: ENABLED
  taskEssentialExitAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: simple-ecs-task-essential-exit-alarm
      EvaluationPeriods: 1
      Statistic: Sum
      Threshold: 2
      AlarmDescription: Alarm if task exited 2 times per minute
      Period: 60
      Namespace: AWS/Events
      Dimensions:
      - Name: RuleName
        Value: !Ref taskEssentialExitEventRule
      ComparisonOperator: GreaterThanOrEqualToThreshold
      MetricName: TriggeredRules
  taskFailedHealthCheckEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: simple-ecs-task-failed-healthcheck-rule
      Description: "Rule which keeps record of task exit events"
      EventPattern: !Sub 
        - | 
            {
              "source": [
                "aws.ecs"
              ],
              "detail-type": [
                "ECS Task State Change"
              ],
              "detail": {
                "clusterArn": ["arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ecsCluster}"],
                "taskDefinitionArn": ["${taskDefinition}"],
                "stoppedReason": ["Task failed ELB health checks in (target-group ${targetGroupLbArns})"]
              }
            }
        - ecsCluster: 
            Fn::ImportValue: simple-cluster-logical-id
          targetGroupLbArns:
            !Ref targetGroup
      State: ENABLED
  taskFailedHealthCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: simple-ecs-healthcheck-fail-alarm
      EvaluationPeriods: 1
      Statistic: Sum
      Threshold: 2
      AlarmDescription: Alarm if task healt check failed 2 times per minute
      Period: 60
      Namespace: AWS/Events
      Dimensions:
      - Name: RuleName
        Value: !Ref taskFailedHealthCheckEventRule
      ComparisonOperator: GreaterThanOrEqualToThreshold
      MetricName: TriggeredRules
      
Outputs:
  ECSService:
    Value: !GetAtt service.Name
  taskEssentialExitAlarm:
    Value: !GetAtt taskEssentialExitAlarm.Arn
  taskFailedHealthCheck:
    Value: !GetAtt taskFailedHealthCheckAlarm.Arn